# QUESTI SONO QUELLI PER FARE LA MAPPA
goals:
  - name: "goal_1"
    position:
      x: 0.5
      y: 3.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.707107  # YAW = 90째
      w: 0.707107

  - name: "goal_2"
    position:
      x: -0.5
      y: 9.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.866025  # YAW = 120째
      w: 0.5

  - name: "goal_3"
    position:
      x: 4.9
      y: 9.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: -1.0      # YAW = -90째
      w: 0.0

  - name: "goal_4"
    position:
      x: 6.0
      y: 1.4
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.965926  # YAW = 165째
      w: 0.258819

  - name: "goal_5" #dentro al labirinto
    position:
      x: 3.36
      y: 6.94
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 1.0
      w: 0.0

  - name: "goal_6" #angolo sx in alto
    position:
      x: -0.99
      y: 11.99
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 1.0
      w: 0.0

  - name: "goal_7" #angolo dx in alto
    position:
      x: 5.47
      y: 12.34
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 1.0
      w: 0.0

  - name: "goal_8" #prima del punto 4
    position:
      x: 8.01
      y: 6.68
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 1.0
      w: 0.0




  - name: "goal_9" #in basso a dx
    position:
      x: 6.36
      y: -3.68
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 1.0
      w: 0.0


  - name: "goal_10" #muro rosso
    position:
      x: 2.36
      y: -5.68
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 1.0
      w: 0.0



# QUESTI SONO PER ARRIVARE A VEDERE IL MARKER
# goals:
  - name: "goal_11"
    position:
      x: 3.72
      y: -0.74
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: -0.014398  # YAW = -0.08 rad
      w: 0.999896

  - name: "goal_0"
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 0.0













